# Default values for kube-test-container.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 5
image:
  repository: sverrirab/kube-test-container
  tag: v1.2
  pullPolicy: IfNotPresent
service:
  name: kube-test-container
  type: LoadBalancer
  externalPort: 80
  internalPort: 8000
resources:
  limits:
    cpu: "1"
    memory: 50Mi
  requests:
    cpu: "1"
    memory: 10Mi
